---

- hosts: all

  vars_files:
    - /etc/ansible/vault.yml

  become: true

  pre_tasks:


  roles:
  # - Benaud12.docker-pi

  tasks:
    
    - name: install dependencies
      apt: name=sysstat

    - name: Install Datadog
      environment:
        DD_API_KEY: "{{ vault_datadog_api_key }}"
      shell: /bin/sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
