---

- hosts: all


  become: true


  vars_files:
    - /etc/ansible/vault.yml

  vars:
    datadog_agent: dd-agent



  tasks:
    
    - name: install dependencies
      apt: name=sysstat

    - name: Install Datadog
      environment:
        DD_API_KEY: "{{ vault_datadog_api_key }}"
      shell: /bin/sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
      async: true
      
    - name: Startup template
      template: src=templates/datadog.service.j2 dest=/etc/systemd/system/dd-agent.service mode=0644

    - name: Enable {{ datadog_agent }}
      systemd:
        name: "{{ datadog_agent }}"
        daemon_reload: yes
        state: started
        enabled: true

    - name: Enable {{ datadog_agent }} with service
      service: name={{ datadog_agent }} enabled=true state=started